config/routes.rb
Rails.application.routes.draw do
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "pages#home"
  resources :surveys, only: [:show] do
  	resources :survey_responses, only: [:new, :destroy]
  end

  resources :questions, only:[:show] do
  	resources :answers, only:[:new, :create]
  end

  resource :profile, only: [:update, :edit, :show] do
    resource :shipping_address, only: [:update, :edit]
  end

  resources :products, only: [:index, :show]

  resources :cart_items

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :survey_response
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/fit_bottom.rb
class FitBottom < ApplicationRecord
end

app/models/fit_top.rb
class FitTop < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  monetize :product_price_cents
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  mount_uploader :photo, PhotoUploader
  monetize :sale_price_cents, :cost_price_cents, :rrp_cents
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :survey_responses
	has_many :shipping_addresses
	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers
end

app/models/survey.rb
class Survey < ApplicationRecord
	has_many :questions
	has_many :survey_responses
end

app/models/survey_response.rb
class SurveyResponse < ApplicationRecord
  # belongs_to :profile
  belongs_to :survey
  belongs_to :profile

  has_many :answers, dependent: :destroy
  has_many :answered_questions, class_name: :Question, source: :question, through: :answers

  def unanswered_questions
  	survey.questions - answered_questions
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :cart_items
  has_many :orders
  has_many :order_items, through: :order
  after_create :create_profile

  private 

  def create_profile
  	# user = self
  	Profile.create!(user: self)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Title & Description -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
    <!-- Stylesheets-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag "favicon.png" %>
  </head>

  <body>
    <!-- This is the generic wrapper for the entire body including header, page content and footer -->
    <div class="generic-page-wrapper">
      <!-- This is the generic wrapper for header and page content Excludes footer-->
      <div class="generic-page-wrapper-content">


    <!-- navbar -->
    <!--     this if statement is for not showing navbar in survey page -->
      <% if content_for?(:navbar) %>
        <%= yield(:navbar) %>
      <% else %>
        <%= render 'shared/navbar' %>
      <% end %>
      <!-- This is for alerts -->
      <%= render 'shared/flashes' %>

      <%= yield %>

      <!-- footer -->
      <!-- this if statement is for not showing footer in survey page -->
    </div>
      <!-- This is a generic wrapper which will allow us to target footer and ensure remains fixed on all pages -->
      <div class="generic-page-wrapper-footer">
        <% if content_for?(:footer) %>
          <%= yield(:footer) %>
        <% else %>
          <%= render 'shared/footer' %>
        <% end %>
      </div>
    </div>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/bondichi/kel.x"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="https://www.lewagon.com/melbourne"><i class="fas fa-bus"></i></a>
  </div>
  <div class="footer-text">
    <a href="#">FAQs</a> /
    <a href="#">Privacy Policy</a> /
    <a href="#">Terms and Conditions</a> /
    <a href="#">About us</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "SHOPPING CART", cart_items_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% unless user_signed_in? %>
      <%= link_to "SIGN UP / LOG IN", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>


    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "dropdown.png", class: "avatar dropdown-toggle", width: 35 , height: 35, id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_profile_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "PROFILE") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "SETTING") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to edit_profile_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "PROFILE") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "SETTING") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</div>