config/routes.rb
Rails.application.routes.draw do
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "pages#home"
  resources :surveys, only: [:show] do
  	resources :survey_responses, only: [:new, :destroy]
  end

  resources :questions, only:[:show] do
  	resources :answers, only:[:new, :create]
  end

  resource :profile, only: [:update, :edit, :show] do
    resource :shipping_address, only: [:update, :edit]
  end

  resources :products, only: [:index, :show]

  resources :cart_items

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :survey_response
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/fit_bottom.rb
class FitBottom < ApplicationRecord
end

app/models/fit_top.rb
class FitTop < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  monetize :product_price_cents
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  mount_uploader :photo, PhotoUploader
  monetize :sale_price_cents, :cost_price_cents, :rrp_cents
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :survey_responses
	has_many :shipping_addresses
	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :profile
end

app/models/survey.rb
class Survey < ApplicationRecord
	has_many :questions
	has_many :survey_responses
end

app/models/survey_response.rb
class SurveyResponse < ApplicationRecord
  # belongs_to :profile
  belongs_to :survey
  belongs_to :profile

  has_many :answers, dependent: :destroy
  has_many :answered_questions, class_name: :Question, source: :question, through: :answers

  def unanswered_questions
  	survey.questions - answered_questions
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :cart_items
  has_many :orders
  has_many :order_items, through: :order
  after_create :create_profile

  private 

  def create_profile
  	# user = self
  	Profile.create!(user: self)
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:destroy, :new]
  # before_action :set_user

  def index
    @cart_items = current_user.cart_items
    @cart_items_tops = @cart_items.select {|cart_item| cart_item.product.category == "TOPS"}
    @cart_items_bottoms = @cart_items.select {|cart_item| cart_item.product.category == "BOTTOMS"}
    @sub_total_tops = @cart_items_tops.map { |item| item.quantity * item.product.sale_price }.sum
    @sub_total_bottoms = @cart_items_bottoms.map { |item| item.quantity * item.product.sale_price }.sum
    @sum_total = @cart_items.map { |item| item.quantity * item.product.sale_price }.sum
  end

  def show
  end

  def new
  end

  def create
    if @cart_item = CartItem.find_by(user: current_user, product_id: cart_item_params[:product_id])
      # already exist, update the item and increate the quantity
      @cart_item.quantity += 1
    else
      # create new cart item
      @cart_item = CartItem.new(cart_item_params)
      @cart_item.quantity = 1
      @cart_item.user = current_user
    end

    if @cart_item.save!
      redirect_back fallback_location: '/'
    else
      # needs to be fixed up - better error message.
      return "please try again"
    end
  end

  def edit
  end

  # def update
  #   if @cart_item.update(cart_item_params)
  #     @cart_item.user = current_user
  #     # authorize @cart_item
  #     # redirect_to cart_item_path(@cart_item)
  #   else
  #     render :edit
  #   end
  # end

  def destroy
    @cart_item.destroy
    redirect_to cart_items_path
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:product_id)
  end

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  # def set_user
  #   @cart_item.user = current_user
  # end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/cart_items/index.html.erb
<!-- setting specific meta tags for page tab -->
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]}-Shopping Cart" %>
<!-- setting specific meta tags external sites -->

<div class="shopping-cart-page-wrapper">
  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <div class="cart-page-main">
        <div class="cart-page-welcome">
          <h2>Your Kel-X Shopping Cart</h2>
        </div>

        <div class="cart-table">
          <% if @cart_items_tops != [] %>
          <h3>TOPS</h3>
          <div class="cart-table-section">
            <div class="cart-table-header">
              <div class="row">
                <div class="col-md-2">Item</div>
                <div class="col-md-4">Description</div>
                <div class="col-md-2 text-right">Quantity</div>
                <div class="col-md-2 text-right">Price</div>
                <div class="col-md-2">Action</div>
              </div>
            </div>
            <% @cart_items_tops.each do |top| %>
            <div class="row cart-table-row">
              <div class="col-md-2">
                <%=  link_to product_path(top.product_id) do %>
                  <div class="cart-image-container">
                  <img class= "cart-image" src=<%= cl_image_path top.product.photo %> alt="Image of selected clothing item">
                  </div>
                <% end %>
              </div>
              <div class="col-md-4"><%= top.product.description %></div>
              <div class="col-md-2 text-right"><%= top.quantity %></div>
              <div class="col-md-2 text-right"><%= humanized_money_with_symbol(top.product.sale_price * top.quantity) %></div>
              <div class="col-md-2"><%= link_to "Remove", cart_item_path(top), :method => :delete, :confirm => "Are you sure?", class: 'btn btn-default shaded-rounded-btn' %></div>
            </div>
          <% end %>
            <div class="row sub-total-row">
              <div class="col-md-8 text-right">Subtotal</div>
              <div class="col-md-2 text-right"><%= humanized_money_with_symbol(@sub_total_tops)%></div>
            </div>
          </div>
          <% end %>

          <% if @cart_items_bottoms != [] %>
          <h3>BOTTOMS</h3>
          <div class="cart-table-section">
            <div class="cart-table-header">
              <div class="row">
                <div class="col-md-2">Item</div>
                <div class="col-md-4">Description</div>
                <div class="col-md-2 text-right">Quantity</div>
                <div class="col-md-2 text-right">Price</div>
                <div class="col-md-2">Action</div>
              </div>
            </div>
            <% @cart_items_bottoms.each do |bottom| %>
            <div class="row cart-table-row">
              <div class="col-md-2">
                <%=  link_to product_path(bottom.product_id) do %>
                  <div class="cart-image-container">
                  <img class= "cart-image" src=<%= cl_image_path bottom.product.photo %> alt="Image of selected clothing item">
                  </div>
                <% end %>
              </div>
              <div class="col-md-4"><%= bottom.product.description %></div>
              <div class="col-md-2 text-right"><%= bottom.quantity %></div>
              <div class="col-md-2 text-right"><%= humanized_money_with_symbol(bottom.product.sale_price * bottom.quantity) %></div>
              <div class="col-md-2"><%= link_to "Remove", cart_item_path(bottom), :method => :delete, :confirm => "Are you sure?", class: 'btn btn-default shaded-rounded-btn' %></div>
            </div>
          <% end %>
            <div class="row sub-total-row">
              <div class="col-md-8 text-right">Subtotal</div>
              <div class="col-md-2 text-right"><%= humanized_money_with_symbol(@sub_total_bottoms)%></div>
            </div>
          </div>
          <% end %>
          <div class="cart-cta-section">
            <div class="cart-page-back-to-recs">
              <%= link_to products_path do %><span class="glyphicon glyphicon-menu-left arrow-glyph-btn-small"></span>BACK TO RECOMMENDATIONS<% end %>
            </div>
            <div class="cart-table-footer"><span class= "sum-total-text">Sum Total:</span><%= humanized_money_with_symbol(@sum_total)%>
            <%= link_to edit_profile_shipping_address_path, class: 'btn-group-lg btn-danger btn-lg small-submit-button' do %>CHECKOUT <span class="glyphicon glyphicon-menu-right arrow-glyph-btn-small"></span>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>