config/routes.rb
Rails.application.routes.draw do
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "pages#home"
  resources :surveys, only: [:show] do
  	resources :survey_responses, only: [:new, :destroy]
  end

  resources :questions, only:[:show] do
  	resources :answers, only:[:new, :create]
  end

  resource :profile, only: [:update, :edit, :show] do
    resource :shipping_address, only: [:update, :edit]
  end

  resources :products, only: [:index, :show]

  resources :cart_items

  resources :orders, only: [:show, :create] do
    resources :payments, only: [:new, :create]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :survey_response
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/fit_bottom.rb
class FitBottom < ApplicationRecord
end

app/models/fit_top.rb
class FitTop < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  monetize :amount_cents
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  monetize :product_price_cents
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  mount_uploader :photo, PhotoUploader
  monetize :sale_price_cents, :cost_price_cents, :rrp_cents
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_many :survey_responses
	has_many :shipping_addresses
	belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :answers
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :profile
end

app/models/survey.rb
class Survey < ApplicationRecord
	has_many :questions
	has_many :survey_responses
end

app/models/survey_response.rb
class SurveyResponse < ApplicationRecord
  # belongs_to :profile
  belongs_to :survey
  belongs_to :profile

  has_many :answers, dependent: :destroy
  has_many :answered_questions, class_name: :Question, source: :question, through: :answers

  def unanswered_questions
  	survey.questions - answered_questions
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :cart_items
  has_many :orders
  has_many :order_items, through: :order
  after_create :create_profile

  private 

  def create_profile
  	# user = self
  	Profile.create!(user: self)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	before_action :set_order

  def new
    @cart_items = current_user.cart_items
    @shipping = ShippingAddress.find(current_user.profile.shipping_address_ids.first)
  end

  def create
    customer = Stripe::Customer.create(
       source: params[:stripeToken],
       email:  params[:stripeEmail]
     )

     charge = Stripe::Charge.create(
       customer:     customer.id,   # You should store this customer id and re-use it.
       amount:       @order.amount_cents,
       description:  "Payment for #{@order.user}'s products for order #{@order.id}",
       currency:     @order.amount.currency
     )

    @order.update(payment: charge.to_json, state: 'paid')
    redirect_to order_path(@order)

  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to order_path(@order)
  end

	private

  def set_order
    @order = current_user.orders.where(state: 'pending').find(params[:order_id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/meta_tags_helper.rb
# These are helpers that will encapsulate the following logic for our 3 keys
# :meta_title
# :meta_description
# :meta_image

# In any view, if a content_for(:meta_key) was defined, it should override DEFAULT_META's value.

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/payments/new.html.erb
<!-- setting specific meta tags for page tab -->
<% content_for :meta_title, "#{DEFAULT_META["meta_product_name"]}-Your payment details" %>

<br>
<div class="checkout-header">
  <h1 style="font-size:59px;">Kel.X - Final Checkout</h1>
</div>

<div class="wrapper-checkout">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-4">
      <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-4">
          <ul class="list-group list-group-flush">
            <li class="list-group-item" style="width:400px; font-weight: bold; font-size: 28px; background-color: #212529; color: white;height:61px;">Customer Information </li>
            <li class="list-group-item" style="width:400px; font-size: 20px;    padding: 23px 16px;"><strong>Name :</strong> <%= current_user.profile.first_name %> <%= current_user.profile.last_name %></li>
            <li class="list-group-item" style="width:400px; font-size: 20px;    padding: 23px 16px;"> <strong>Delivery Address :</strong> <%= @shipping.number %>, <%= @shipping.street %>, <%= @shipping.suburb %>, <%= @shipping.post_code %>, <%= @shipping.state %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-md-6 container-item">
      <table class="table table-striped">
        <div class="row">
          <div class="col-xs-12 col-sm-6 col-md-4">
            <thead class="thead-dark">
              <tr>
                <th scope="col" style="height:61px; vertical-align: middle">PRODUCT</th>
                <th scope="col" style="height:61px; vertical-align: middle"></th>
                <th scope="col" style="height:61px; vertical-align: middle">QTY</th>
                <th style="min-width: 100px;height: 61px; vertical-align: middle" scope="col">Total</th>
                <th scope="col" style="height:61px; vertical-align: middle"></th>
              </tr>
            </thead>
            <tbody>
              <% @cart_items.each do |cart_item| %>
                <tr>
                  <td>
                    <img class= "cart-image" src=<%= cl_image_path cart_item.product.photo %> alt="Image of selected clothing item"></td>
                  <td><%= cart_item.product.description %></td>
                  <td><%= cart_item.quantity %></td>
                  <td><%= humanized_money_with_symbol(cart_item.product.sale_price * cart_item.quantity) %></td>
                  <td><%= link_to "×", cart_item_path(cart_item), :method => :delete, :confirm => "Are you sure?", class: 'cart-delete-button' %></td>
                </tr>
              <% end %>
              <tr>
                <th scope="row" style="font-size:40px; text-align: right;"></th>
                <td colspan="4">
                  <%= form_tag order_payments_path(@order) do %>
                    <div class="checkout_button">
                      <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-name="My Kelx Orders"
                        data-email="<%= current_user.email %>"
                        data-description="Products <%= @order.id %>"
                        data-amount="<%= @order.amount_cents %>"
                        data-label="PAY <%= humanized_money_with_symbol(@order.amount) %>"
                        data-currency="<%= @order.amount.currency %>"></script>
                    </div>
                  <% end %>
                </td>
              </tr>
            </tbody>
          </div>
        </div>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div>

<!-- PUT PROFILE INFO -->

  <div class="container-item">

  </div>

</div>